# On quarto websites, see https://quarto.org/docs/reference/projects/websites.html
# On publishing with github pages, see https://quarto.org/docs/publishing/github-pages.html
project:
  type: website
  output-dir: docs

# see https://quarto.org/docs/websites/website-navigation.html
website:
  title: "Public Pressure"
  image: ""
  navbar:
    left:
      - href: slides/index.qmd
        text: Slides


format:
 html:
   toc: true
   toc-location: left
   theme: michigan.scss
   include-after-body: assets/accessibility-fixes.js
   # accessibility checks; see https://quarto.org/docs/output-formats/html-accessibility.html
   axe:
    output: console
    # output: document # Makes accessability report appear on the web pages

number-depth: 3

execute:
  freeze: auto  # re-render code only when source file changes

bibliography: assets/dissertation.bib
